Repository viur-framework/viur-toolkit, pull requests merged in 2024-10, with the labels that each got.

#17 feat: Add `only_parameter` and `exclude_parameter` to `@debug` decorator
  src/viur/toolkit/decorators.py
Labels: Priority: Medium, enhancement, version-target:minor

#22 fix: `Importer.logout` only when there is a login-method
  src/viur/toolkit/importer/importer.py
Labels: Priority: Medium, bug, version-target:patch

#23 chore(deps-fix): Lock `mypy` to `1.11.X`
  .github/workflows/pep8.yaml
  Pipfile
  Pipfile.lock
Labels: Priority: High, bug, dependencies, version-target:patch, cicd

#19 feat: Support `viur-core>=3.7`; Use `_private_bucket` for reports' storage place
  src/viur/toolkit/report.py
Labels: Priority: High, enhancement, version-target:minor

#27 feat: Add support for singleton imports
  src/viur/toolkit/importer/importable.py
Labels: Priority: High, enhancement, version-target:minor

#25 fix: `db.set_status()` can't be called within a transaction
  src/viur/toolkit/db.py
Labels: bug, hotfix

#26 fix: Require `mypy` only in dev-packages
  Pipfile
  Pipfile.lock
Labels: Priority: Low, invalid, version-target:patch
