Repository viur-framework/viur-toolkit, pull requests merged in 2025-01, with the labels that each got.

#39 feat: Import facilities for `FileBone(public=True)`
  src/viur/toolkit/importer/importer.py
Labels: enhancement

#40 feat: `debuglimit` for Importable config
  src/viur/toolkit/importer/importable.py
Labels: enhancement

#41 fix: Simple bones with languages import broken
  src/viur/toolkit/importer/importer.py
Labels: bug

#38 fix: Import mulitple/language `RecordBone`s
  src/viur/toolkit/importer/importer.py
Labels: bug

#44 fix: Handling of missing entity in `db.increase_counter` and `db.write_in_transaction`
  src/viur/toolkit/db.py
Labels: Priority: Critical, bug

#45 fix: Use fresh `import_skel` when importing multiple entries
  src/viur/toolkit/importer/importable.py
Labels: bug
